title: Gen AI and ML
description: My journey through generative AI tools and ideas.
remote_theme: chesterhow/tale  # Use remote_theme instead of theme
lang: en
author:
  name: Saif

# Build settings
markdown: kramdown
highlighter: rouge

# Optional extras
paginate: 5
paginate_path: "/page:num"
permalink: pretty

plugins:
  - jekyll-paginate
  - jekyll-remote-theme  # This is needed for remote themes
